# CI->CD workflow
name: CD Workflow

on:
  push:
    branches: 
      - master
env:
  AZURE_RESOURCEGROUP_NAME: "rg-aa-github-deployment"
  AZURE_WEBAPP_NAME: "as-github-cd-aa"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: |
        npm install
        npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webpack artifact
        path: public/
      
  test:
    needs: [build]
    strategy:
      matrix:
        node-version: [10.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack artifact
          path: public/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, test
        run: |
          npm install
          npm test
        env:
          CI: true
        
  stg-deployment:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az group create -n ${{ env.AZURE_RESOURCEGROUP_NAME }} -l australiasoutheast 
          az deployment group create -n ghaction -g ${{ env.AZURE_RESOURCEGROUP_NAME }} --template-file deployment/azuredeploy.json
      - name: 'Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: 'public/' 
      - name: logout
        run: |
          az logout
